### ISSUE TITLE
Corrupt file created if there are special characters in the title

### ISSUE THREAD

**Issue by Reda2200** [paolodelfino/movie-downloader#1]
Hi, it is a very interesting and well done project, but when downloading movies that contain special characters in the name, the file is saved incorrectly resulting with size of 0 bytes and without extension (broken video), because windows cannot create files with special characters such as the colon ( : ). See images below. Is there any way to solve it?
![Screenshot_1](https://github.com/paolodelfino/movie-downloader/assets/119880230/78ebfdd4-8d80-46b4-ad99-f36f9ce8db7a)
![Screenshot_2](https://github.com/paolodelfino/movie-downloader/assets/119880230/8a3cb9cd-3923-48c7-aca3-f291748f38e5)

**Comment by Reda2200** [comment]
I have added a pull request to correct this problem, let me know if it is the right way

**Comment by paolodelfino** [comment]
I merged the pull request, thank you so much!
